services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: ytdlp-tguserbot
        restart: unless-stopped
        working_dir: /usr/src/app
        volumes:
          - ./:/usr/src/app
          - /main/docker-compose/tg-botapi/data:/var/lib/telegram-bot-api
        networks:
          - telegram-bot-api

networks:
  telegram-bot-api:
    external: true
