version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: ytdlp-tguserbot
        restart: unless-stopped
        working_dir: /usr/src/app
        volumes:
          - /main/ytdlp-tguserbot/:/usr/src/app
